### ISSUE TITLE
alsaaudio.ALSAAudioError: No such file or directory [default]

### ISSUE THREAD

**Issue by wipfli** [ballometer/BallometerOS#109]
Mic is not working, last worked in January 2023, fails with error:

```
# python hardware_tests/test_all.py 
###### test_bmp
test_temperature()
test_pressure()
###### test_lcd
test_cursor_pos()
test_columns()
test_cursor_mode()
test_clear()
test_write_string()
###### test_lsm
test_accel_x()
test_accel_y()
test_accel_z()
test_mag_x()
test_mag_y()
test_mag_z()
###### test_sht
test_temperature()
test_humidity()
###### test_tsl
test_visible()
test_infrared()
###### skip test_wifi
###### test_mic
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM default
Traceback (most recent call last):
  File "/root/ballometer/hardware_tests/test_all.py", line 29, in <module>
    test_mic.test_all()
  File "/root/ballometer/hardware_tests/test_mic.py", line 5, in test_all
    mic = ballometer.Mic()
          ^^^^^^^^^^^^^^^^
  File "/root/ballometer/ballometer/mic.py", line 8, in __init__
    self._inp = alsaaudio.PCM(
                ^^^^^^^^^^^^^^

```

**Comment by wipfli** [comment]
Happens also with v2.1.4 from 2022, seems like a hardware failure
